# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
User.create!([
  {name: "Adam", email: "adamin@gmail.com", password_digest: "a"},
  {name: "Ben", email: "ben@gmail.com", password_digest: "a"},
  {name: "Charlie", email: "charlie@gmail.com", password_digest: "a"},
  {name: "Don", email: "don@gmail.com", password_digest: "a"},
  {name: "Amy", email: "amy@gmail.com", password_digest: "a"},
  {name: "Barbara", email: "barbara@gmail.com", password_digest: "a"},
  {name: "Cathy", email: "cathy@gmail.com", password_digest: "a"},
  {name: "Delores", email: "delores@gmail.com", password_digest: "a"},
  {name: "Mary", email: "mary@gmail.com", password_digest: "a"},
  {name: "Sara", email: "sara@gmail.com", password_digest: "a"},
  {name: "Jose", email: "jose@gmail.com", password_digest: "a"},
  {name: "Juan", email: "juan@gmail.com", password_digest: "a"},
  {name: "Manuel", email: "manuel@gmail.com", password_digest: "a"},
  {name: "Erik", email: "erik@gmail.com", password_digest: "a"},
  {name: "Joe", email: "joe@gmail.com", password_digest: "a"},
  {name: "Svetlana", email: "sveta@gmail.com", password_digest: "a"},
  {name: "Sergei", email: "sergei@gmail.com", password_digest: "a"},
  {name: "Dima", email: "dima@gmail.com", password_digest: "a"},
  {name: "Ivan", email: "ivan@gmail.com", password_digest: "a"},
  {name: "Jorge", email: "jorge@gmail.com", password_digest: "a"},
  {name: "Bill", email: "bill@gmail.com", password_digest: "a"},
  ])

Quest.create!([
  {name: "Quest1", description: "Quest1 of awesomeness", start: "2017-07-04 12:30:00", user_id: 1, invite_msg: "Get ready for the quest!", start_msg: "Have fun Questing!", final_msg: "Great job on the Quest!"},
  {name: "Quest2", description: "Quest2 of awesomeness", start: "2017-07-04 13:30:00", user_id: 2, invite_msg: "Get ready for the quest!", start_msg: "Have fun Questing!", final_msg: "Great job on the Quest!"},
  {name: "Quest3", description: "Quest3 of awesomeness", start: "2017-07-04 14:30:00", user_id: 3, invite_msg: "Get ready for the quest!", start_msg: "Have fun Questing!", final_msg: "Great job on the Quest!"},
  {name: "Quest4", description: "Quest4 of awesomeness", start: "2017-07-04 15:30:00", user_id: 4, invite_msg: "Get ready for the quest!", start_msg: "Have fun Questing!", final_msg: "Great job on the Quest!"},
  {name: "Quest5", description: "Quest5 of awesomeness", start: "2017-07-04 16:30:00", user_id: 5, invite_msg: "Get ready for the quest!", start_msg: "Have fun Questing!", final_msg: "Great job on the Quest!"},
  {name: "Quest6", description: "Quest6 of awesomeness", start: "2017-07-04 17:30:00", user_id: 6, invite_msg: "Get ready for the quest!", start_msg: "Have fun Questing!", final_msg: "Great job on the Quest!"},
  {name: "Quest7", description: "Quest7 of awesomeness", start: "2017-07-04 18:30:00", user_id: 7, invite_msg: "Get ready for the quest!", start_msg: "Have fun Questing!", final_msg: "Great job on the Quest!"},
  {name: "Quest8", description: "Quest8 of awesomeness", start: "2017-07-04 19:30:00", user_id: 8, invite_msg: "Get ready for the quest!", start_msg: "Have fun Questing!", final_msg: "Great job on the Quest!"},
  {name: "Quest9", description: "Quest9 of awesomeness", start: "2017-07-04 20:30:00", user_id: 9, invite_msg: "Get ready for the quest!", start_msg: "Have fun Questing!", final_msg: "Great job on the Quest!"},
  {name: "Quest10", description: "Quest10 of awesomeness", start: "2017-07-04 21:30:00", user_id: 10, invite_msg: "Get ready for the quest!", start_msg: "Have fun Questing!", final_msg: "Great job on the Quest!"},
  ])

Task.create!([
  {name: "Task1", description: "Task 1 of Quest 1", answer: "Task Answer", quest_id: 1, clue1: "Something Witty to Help You!", clue2: "Something sarcastic to anger you!", clue3: "Something snarky to really piss you off!", clue_timer: 2, answer_check: false, answer_comment: "Great job!", skip_comment: "Quitter!"},
  {name: "Task2", description: "Task 2 of Quest 1", answer: "Task Answer", quest_id: 1, clue1: "Something Witty to Help You!", clue2: "Something sarcastic to anger you!", clue3: "Something snarky to really piss you off!", clue_timer: 2, answer_check: false, answer_comment: "Great job!", skip_comment: "Quitter!"},
  {name: "Task3", description: "Task 3 of Quest 1", answer: "Task Answer", quest_id: 1, clue1: "Something Witty to Help You!", clue2: "Something sarcastic to anger you!", clue3: "Something snarky to really piss you off!", clue_timer: 2, answer_check: false, answer_comment: "Great job!", skip_comment: "Quitter!"},
  {name: "Task4", description: "Task 4 of Quest 1", answer: "Task Answer", quest_id: 1, clue1: "Something Witty to Help You!", clue2: "Something sarcastic to anger you!", clue3: "Something snarky to really piss you off!", clue_timer: 2, answer_check: false, answer_comment: "Great job!", skip_comment: "Quitter!"},
  {name: "Task5", description: "Task 5 of Quest 1", answer: "Task Answer", quest_id: 1, clue1: "Something Witty to Help You!", clue2: "Something sarcastic to anger you!", clue3: "Something snarky to really piss you off!", clue_timer: 2, answer_check: false, answer_comment: "Great job!", skip_comment: "Quitter!"},
  {name: "Task1", description: "Task 1 of Quest 2", answer: "Task Answer", quest_id: 2, clue1: "Something Witty to Help You!", clue2: "Something sarcastic to anger you!", clue3: "Something snarky to really piss you off!", clue_timer: 2, answer_check: false, answer_comment: "Great job!", skip_comment: "Quitter!"},
  {name: "Task2", description: "Task 2 of Quest 2", answer: "Task Answer", quest_id: 2, clue1: "Something Witty to Help You!", clue2: "Something sarcastic to anger you!", clue3: "Something snarky to really piss you off!", clue_timer: 2, answer_check: false, answer_comment: "Great job!", skip_comment: "Quitter!"},
  {name: "Task3", description: "Task 3 of Quest 2", answer: "Task Answer", quest_id: 2, clue1: "Something Witty to Help You!", clue2: "Something sarcastic to anger you!", clue3: "Something snarky to really piss you off!", clue_timer: 2, answer_check: false, answer_comment: "Great job!", skip_comment: "Quitter!"},
  {name: "Task4", description: "Task 4 of Quest 2", answer: "Task Answer", quest_id: 2, clue1: "Something Witty to Help You!", clue2: "Something sarcastic to anger you!", clue3: "Something snarky to really piss you off!", clue_timer: 2, answer_check: false, answer_comment: "Great job!", skip_comment: "Quitter!"},
  {name: "Task5", description: "Task 5 of Quest 2", answer: "Task Answer", quest_id: 2, clue1: "Something Witty to Help You!", clue2: "Something sarcastic to anger you!", clue3: "Something snarky to really piss you off!", clue_timer: 2, answer_check: false, answer_comment: "Great job!", skip_comment: "Quitter!"},
  {name: "Task1", description: "Task 1 of Quest 3", answer: "Task Answer", quest_id: 3, clue1: "Something Witty to Help You!", clue2: "Something sarcastic to anger you!", clue3: "Something snarky to really piss you off!", clue_timer: 2, answer_check: false, answer_comment: "Great job!", skip_comment: "Quitter!"},
  {name: "Task2", description: "Task 2 of Quest 3", answer: "Task Answer", quest_id: 3, clue1: "Something Witty to Help You!", clue2: "Something sarcastic to anger you!", clue3: "Something snarky to really piss you off!", clue_timer: 2, answer_check: false, answer_comment: "Great job!", skip_comment: "Quitter!"},
  {name: "Task3", description: "Task 3 of Quest 3", answer: "Task Answer", quest_id: 3, clue1: "Something Witty to Help You!", clue2: "Something sarcastic to anger you!", clue3: "Something snarky to really piss you off!", clue_timer: 2, answer_check: false, answer_comment: "Great job!", skip_comment: "Quitter!"},
  {name: "Task1", description: "Task 1 of Quest 4", answer: "Task Answer", quest_id: 4, clue1: "Something Witty to Help You!", clue2: "Something sarcastic to anger you!", clue3: "Something snarky to really piss you off!", clue_timer: 2, answer_check: false, answer_comment: "Great job!", skip_comment: "Quitter!"},
  {name: "Task2", description: "Task 2 of Quest 4", answer: "Task Answer", quest_id: 4, clue1: "Something Witty to Help You!", clue2: "Something sarcastic to anger you!", clue3: "Something snarky to really piss you off!", clue_timer: 2, answer_check: false, answer_comment: "Great job!", skip_comment: "Quitter!"},
  {name: "Task3", description: "Task 3 of Quest 4", answer: "Task Answer", quest_id: 4, clue1: "Something Witty to Help You!", clue2: "Something sarcastic to anger you!", clue3: "Something snarky to really piss you off!", clue_timer: 2, answer_check: false, answer_comment: "Great job!", skip_comment: "Quitter!"},
  {name: "Task4", description: "Task 4 of Quest 4", answer: "Task Answer", quest_id: 4, clue1: "Something Witty to Help You!", clue2: "Something sarcastic to anger you!", clue3: "Something snarky to really piss you off!", clue_timer: 2, answer_check: false, answer_comment: "Great job!", skip_comment: "Quitter!"},
  {name: "Task5", description: "Task 5 of Quest 4", answer: "Task Answer", quest_id: 4, clue1: "Something Witty to Help You!", clue2: "Something sarcastic to anger you!", clue3: "Something snarky to really piss you off!", clue_timer: 2, answer_check: false, answer_comment: "Great job!", skip_comment: "Quitter!"},
  {name: "Task6", description: "Task 6 of Quest 4", answer: "Task Answer", quest_id: 4, clue1: "Something Witty to Help You!", clue2: "Something sarcastic to anger you!", clue3: "Something snarky to really piss you off!", clue_timer: 2, answer_check: false, answer_comment: "Great job!", skip_comment: "Quitter!"},
  {name: "Task7", description: "Task 7 of Quest 4", answer: "Task Answer", quest_id: 4, clue1: "Something Witty to Help You!", clue2: "Something sarcastic to anger you!", clue3: "Something snarky to really piss you off!", clue_timer: 2, answer_check: false, answer_comment: "Great job!", skip_comment: "Quitter!"},
  {name: "Task1", description: "Task 1 of Quest 5", answer: "Task Answer", quest_id: 5, clue1: "Something Witty to Help You!", clue2: "Something sarcastic to anger you!", clue3: "Something snarky to really piss you off!", clue_timer: 2, answer_check: false, answer_comment: "Great job!", skip_comment: "Quitter!"},
  {name: "Task2", description: "Task 2 of Quest 5", answer: "Task Answer", quest_id: 5, clue1: "Something Witty to Help You!", clue2: "Something sarcastic to anger you!", clue3: "Something snarky to really piss you off!", clue_timer: 2, answer_check: false, answer_comment: "Great job!", skip_comment: "Quitter!"},
  {name: "Task3", description: "Task 3 of Quest 5", answer: "Task Answer", quest_id: 5, clue1: "Something Witty to Help You!", clue2: "Something sarcastic to anger you!", clue3: "Something snarky to really piss you off!", clue_timer: 2, answer_check: false, answer_comment: "Great job!", skip_comment: "Quitter!"},
  {name: "Task1", description: "Task 1 of Quest 6", answer: "Task Answer", quest_id: 6, clue1: "Something Witty to Help You!", clue2: "Something sarcastic to anger you!", clue3: "Something snarky to really piss you off!", clue_timer: 2, answer_check: false, answer_comment: "Great job!", skip_comment: "Quitter!"},
  {name: "Task2", description: "Task 2 of Quest 6", answer: "Task Answer", quest_id: 6, clue1: "Something Witty to Help You!", clue2: "Something sarcastic to anger you!", clue3: "Something snarky to really piss you off!", clue_timer: 2, answer_check: false, answer_comment: "Great job!", skip_comment: "Quitter!"},
  {name: "Task3", description: "Task 3 of Quest 6", answer: "Task Answer", quest_id: 6, clue1: "Something Witty to Help You!", clue2: "Something sarcastic to anger you!", clue3: "Something snarky to really piss you off!", clue_timer: 2, answer_check: false, answer_comment: "Great job!", skip_comment: "Quitter!"},
  {name: "Task4", description: "Task 4 of Quest 6", answer: "Task Answer", quest_id: 6, clue1: "Something Witty to Help You!", clue2: "Something sarcastic to anger you!", clue3: "Something snarky to really piss you off!", clue_timer: 2, answer_check: false, answer_comment: "Great job!", skip_comment: "Quitter!"},
  {name: "Task5", description: "Task 5 of Quest 6", answer: "Task Answer", quest_id: 6, clue1: "Something Witty to Help You!", clue2: "Something sarcastic to anger you!", clue3: "Something snarky to really piss you off!", clue_timer: 2, answer_check: false, answer_comment: "Great job!", skip_comment: "Quitter!"},
  {name: "Task6", description: "Task 6 of Quest 6", answer: "Task Answer", quest_id: 6, clue1: "Something Witty to Help You!", clue2: "Something sarcastic to anger you!", clue3: "Something snarky to really piss you off!", clue_timer: 2, answer_check: false, answer_comment: "Great job!", skip_comment: "Quitter!"},
  {name: "Task7", description: "Task 7 of Quest 6", answer: "Task Answer", quest_id: 6, clue1: "Something Witty to Help You!", clue2: "Something sarcastic to anger you!", clue3: "Something snarky to really piss you off!", clue_timer: 2, answer_check: false, answer_comment: "Great job!", skip_comment: "Quitter!"},
  {name: "Task1", description: "Task 1 of Quest 7", answer: "Task Answer", quest_id: 7, clue1: "Something Witty to Help You!", clue2: "Something sarcastic to anger you!", clue3: "Something snarky to really piss you off!", clue_timer: 2, answer_check: false, answer_comment: "Great job!", skip_comment: "Quitter!"},
  {name: "Task2", description: "Task 2 of Quest 7", answer: "Task Answer", quest_id: 7, clue1: "Something Witty to Help You!", clue2: "Something sarcastic to anger you!", clue3: "Something snarky to really piss you off!", clue_timer: 2, answer_check: false, answer_comment: "Great job!", skip_comment: "Quitter!"},
  {name: "Task3", description: "Task 3 of Quest 7", answer: "Task Answer", quest_id: 7, clue1: "Something Witty to Help You!", clue2: "Something sarcastic to anger you!", clue3: "Something snarky to really piss you off!", clue_timer: 2, answer_check: false, answer_comment: "Great job!", skip_comment: "Quitter!"},
  {name: "Task4", description: "Task 4 of Quest 7", answer: "Task Answer", quest_id: 7, clue1: "Something Witty to Help You!", clue2: "Something sarcastic to anger you!", clue3: "Something snarky to really piss you off!", clue_timer: 2, answer_check: false, answer_comment: "Great job!", skip_comment: "Quitter!"},
  {name: "Task5", description: "Task 5 of Quest 7", answer: "Task Answer", quest_id: 7, clue1: "Something Witty to Help You!", clue2: "Something sarcastic to anger you!", clue3: "Something snarky to really piss you off!", clue_timer: 2, answer_check: false, answer_comment: "Great job!", skip_comment: "Quitter!"},
  {name: "Task1", description: "Task 1 of Quest 8", answer: "Task Answer", quest_id: 8, clue1: "Something Witty to Help You!", clue2: "Something sarcastic to anger you!", clue3: "Something snarky to really piss you off!", clue_timer: 2, answer_check: false, answer_comment: "Great job!", skip_comment: "Quitter!"},
  {name: "Task2", description: "Task 2 of Quest 8", answer: "Task Answer", quest_id: 8, clue1: "Something Witty to Help You!", clue2: "Something sarcastic to anger you!", clue3: "Something snarky to really piss you off!", clue_timer: 2, answer_check: false, answer_comment: "Great job!", skip_comment: "Quitter!"},
  {name: "Task3", description: "Task 3 of Quest 8", answer: "Task Answer", quest_id: 8, clue1: "Something Witty to Help You!", clue2: "Something sarcastic to anger you!", clue3: "Something snarky to really piss you off!", clue_timer: 2, answer_check: false, answer_comment: "Great job!", skip_comment: "Quitter!"},
  {name: "Task4", description: "Task 4 of Quest 8", answer: "Task Answer", quest_id: 8, clue1: "Something Witty to Help You!", clue2: "Something sarcastic to anger you!", clue3: "Something snarky to really piss you off!", clue_timer: 2, answer_check: false, answer_comment: "Great job!", skip_comment: "Quitter!"},
  {name: "Task5", description: "Task 5 of Quest 8", answer: "Task Answer", quest_id: 8, clue1: "Something Witty to Help You!", clue2: "Something sarcastic to anger you!", clue3: "Something snarky to really piss you off!", clue_timer: 2, answer_check: false, answer_comment: "Great job!", skip_comment: "Quitter!"},
  {name: "Task1", description: "Task 1 of Quest 9", answer: "Task Answer", quest_id: 9, clue1: "Something Witty to Help You!", clue2: "Something sarcastic to anger you!", clue3: "Something snarky to really piss you off!", clue_timer: 2, answer_check: false, answer_comment: "Great job!", skip_comment: "Quitter!"},
  {name: "Task2", description: "Task 2 of Quest 9", answer: "Task Answer", quest_id: 9, clue1: "Something Witty to Help You!", clue2: "Something sarcastic to anger you!", clue3: "Something snarky to really piss you off!", clue_timer: 2, answer_check: false, answer_comment: "Great job!", skip_comment: "Quitter!"},
  {name: "Task3", description: "Task 3 of Quest 9", answer: "Task Answer", quest_id: 9, clue1: "Something Witty to Help You!", clue2: "Something sarcastic to anger you!", clue3: "Something snarky to really piss you off!", clue_timer: 2, answer_check: false, answer_comment: "Great job!", skip_comment: "Quitter!"},
  {name: "Task1", description: "Task 1 of Quest 10", answer: "Task Answer", quest_id: 10, clue1: "Something Witty to Help You!", clue2: "Something sarcastic to anger you!", clue3: "Something snarky to really piss you off!", clue_timer: 2, answer_check: false, answer_comment: "Great job!", skip_comment: "Quitter!"},
  {name: "Task2", description: "Task 2 of Quest 10", answer: "Task Answer", quest_id: 10, clue1: "Something Witty to Help You!", clue2: "Something sarcastic to anger you!", clue3: "Something snarky to really piss you off!", clue_timer: 2, answer_check: false, answer_comment: "Great job!", skip_comment: "Quitter!"},
  {name: "Task3", description: "Task 3 of Quest 10", answer: "Task Answer", quest_id: 10, clue1: "Something Witty to Help You!", clue2: "Something sarcastic to anger you!", clue3: "Something snarky to really piss you off!", clue_timer: 2, answer_check: false, answer_comment: "Great job!", skip_comment: "Quitter!"},
  {name: "Task4", description: "Task 4 of Quest 10", answer: "Task Answer", quest_id: 10, clue1: "Something Witty to Help You!", clue2: "Something sarcastic to anger you!", clue3: "Something snarky to really piss you off!", clue_timer: 2, answer_check: false, answer_comment: "Great job!", skip_comment: "Quitter!"},
  {name: "Task5", description: "Task 5 of Quest 10", answer: "Task Answer", quest_id: 10, clue1: "Something Witty to Help You!", clue2: "Something sarcastic to anger you!", clue3: "Something snarky to really piss you off!", clue_timer: 2, answer_check: false, answer_comment: "Great job!", skip_comment: "Quitter!"},
  {name: "Task6", description: "Task 6 of Quest 10", answer: "Task Answer", quest_id: 10, clue1: "Something Witty to Help You!", clue2: "Something sarcastic to anger you!", clue3: "Something snarky to really piss you off!", clue_timer: 2, answer_check: false, answer_comment: "Great job!", skip_comment: "Quitter!"},
  {name: "Task7", description: "Task 7 of Quest 10", answer: "Task Answer", quest_id: 10, clue1: "Something Witty to Help You!", clue2: "Something sarcastic to anger you!", clue3: "Something snarky to really piss you off!", clue_timer: 2, answer_check: false, answer_comment: "Great job!", skip_comment: "Quitter!"},
  ])

# Roles.create!([
#   {role: true, user_id: 1, quest_id: 1},
#   {role: false, user_id: 2, quest_id: 1},
#   {role: false, user_id: 3, quest_id: 1},
#   {role: true, user_id: 4, quest_id: 2},
#   {role: false, user_id: 5, quest_id: 2},
#   {role: false, user_id: 6, quest_id: 2},
#   {role: true, user_id: 3, quest_id: 3},
#   {role: false, user_id: 1, quest_id: 3},
#   {role: false, user_id: 5, quest_id: 3},
#   {role: false, user_id: 6, quest_id: 3},
#   {role: true, user_id: 1, quest_id: 4},
#   {role: false, user_id: 7, quest_id: 4},
#   {role: true, user_id: 8, quest_id: 5},
#   {role: false, user_id: 7, quest_id: 5},
#   {role: false, user_id: 9, quest_id: 5},
#   {role: true, user_id: 7, quest_id: 6},
#   {role: false, user_id: 4, quest_id: 6},
#   {role: false, user_id: 5, quest_id: 7},
#   {role: true, user_id: 3, quest_id: 7},
#   {role: false, user_id: 4, quest_id: 8},
#   {role: false, user_id: 10, quest_id: 8},
#   {role: true, user_id: 6, quest_id: 8},
#   {role: false, user_id: 2, quest_id: 9},
#   {role: true, user_id: 10, quest_id: 9},
#   {role: true, user_id: 2, quest_id: 10},
#   {role: false, user_id: 3, quest_id: 10},
#   {role: false, user_id: 9, quest_id: 10},
#   ])
