# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
User.create!([
  {name: "Adam", email: "adamin@gmail.com", password_digest: BCrypt::Password.create('a')},
  {name: "Ben", email: "ben@gmail.com", password_digest: BCrypt::Password.create('a')},
  {name: "Charlie", email: "charlie@gmail.com", password_digest: BCrypt::Password.create('a')},
  {name: "Don", email: "don@gmail.com", password_digest: BCrypt::Password.create('a')},
  {name: "Amy", email: "amy@gmail.com", password_digest: BCrypt::Password.create('a')},
  {name: "Barbara", email: "barbara@gmail.com", password_digest: BCrypt::Password.create('a')},
  {name: "Cathy", email: "cathy@gmail.com", password_digest: BCrypt::Password.create('a')},
  {name: "Delores", email: "delores@gmail.com", password_digest: BCrypt::Password.create('a')},
  {name: "Mary", email: "mary@gmail.com", password_digest: BCrypt::Password.create('a')},
  {name: "Sara", email: "sara@gmail.com", password_digest: BCrypt::Password.create('a')},
  {name: "Jose", email: "jose@gmail.com", password_digest: BCrypt::Password.create('a')},
  {name: "Juan", email: "juan@gmail.com", password_digest: BCrypt::Password.create('a')},
  {name: "Manuel", email: "manuel@gmail.com", password_digest: BCrypt::Password.create('a')},
  {name: "Erik", email: "erik@gmail.com", password_digest: BCrypt::Password.create('a')},
  {name: "Joe", email: "joe@gmail.com", password_digest: BCrypt::Password.create('a')},
  {name: "Svetlana", email: "sveta@gmail.com", password_digest: BCrypt::Password.create('a')},
  {name: "Sergei", email: "sergei@gmail.com", password_digest: BCrypt::Password.create('a')},
  {name: "Dima", email: "dima@gmail.com", password_digest: BCrypt::Password.create('a')},
  {name: "Ivan", email: "ivan@gmail.com", password_digest: BCrypt::Password.create('a')},
  {name: "Jorge", email: "jorge@gmail.com", password_digest: BCrypt::Password.create('a')},
  {name: "Bill", email: "bill@gmail.com", password_digest: BCrypt::Password.create('a')},
  {name: "Shannan", email: "shannan.muench@gmail.com", password_digest: BCrypt::Password.create('a')},
  {name: "Dave", email: "david.w.muench@gmail.com", password_digest: BCrypt::Password.create('a')},
  ])

Quest.create!([
  {name: "Wynwood Quest",
    description: "This quest will take you around Wynwood to find things you never knew were there!",
    start: "2017-07-04 12:30:00",
    user_id: 1,
    invite_msg: "Are you ready for some adventure?! Well, charge up your phone and make sure you have plenty of memory to take some gorgeous photos as you explore Wynwood to complete
    this quest. You won't need anything special for this quest- just your smartphone, comfortable shoes, and money if you want to grab a snack along the way. I had fun making this-
    I hope you have fun completing it!!! The quest will start at Jose De Diego Middle School at 3100 NW 5th Ave (There's free parking there! You're welcome!).",
    start_msg: "It's GO TIME! Make sure you take a photo or selfie at each task and along the way. Post your images to your IG account using #WynwoodQuest and #AmazingQuest so I can
    track your progress. The rules are, you must submit an answer for each quest to move on to the next one. You will receive a few clues along the way (again, you're welcome!) but if
    you really get stumped you can skip a task. If you get really stuck- call or text me! Good Luck!",
    final_msg: "Great job on the Quest! Don't forget to upload your pics with #WynwoodQuest and #AmazingQuest. Now that you are done- head to the Wynwood Yard at 56 NW 29th St and look
    for me- I'll be waiting for you there!},
  {name: "Quest2",
    description: "Quest2 of awesomeness",
    start: "2017-07-04 13:30:00",
    user_id: 2,
    invite_msg: "Get ready for the quest!",
    start_msg: "Have fun Questing!",
    final_msg: "Great job on the Quest!"},
  {name: "Quest3",
    description: "Quest3 of awesomeness",
    start: "2017-07-04 14:30:00",
    user_id: 3,
    invite_msg: "Get ready for the quest!",
    start_msg: "Have fun Questing!",
    final_msg: "Great job on the Quest!"},
  {name: "Quest4",
    description: "Quest4 of awesomeness",
    start: "2017-07-04 15:30:00",
    user_id: 4,
    invite_msg: "Get ready for the quest!",
    start_msg: "Have fun Questing!",
    final_msg: "Great job on the Quest!"},
  {name: "Quest5",
    description: "Quest5 of awesomeness",
    start: "2017-07-04 16:30:00",
    user_id: 5,
    invite_msg: "Get ready for the quest!", start_msg: "Have fun Questing!", final_msg: "Great job on the Quest!"},
  {name: "Quest6", description: "Quest6 of awesomeness", start: "2017-07-04 17:30:00", user_id: 6, invite_msg: "Get ready for the quest!", start_msg: "Have fun Questing!", final_msg: "Great job on the Quest!"},
  {name: "Quest7", description: "Quest7 of awesomeness", start: "2017-07-04 18:30:00", user_id: 7, invite_msg: "Get ready for the quest!", start_msg: "Have fun Questing!", final_msg: "Great job on the Quest!"},
  {name: "Quest8", description: "Quest8 of awesomeness", start: "2017-07-04 19:30:00", user_id: 8, invite_msg: "Get ready for the quest!", start_msg: "Have fun Questing!", final_msg: "Great job on the Quest!"},
  {name: "Quest9", description: "Quest9 of awesomeness", start: "2017-07-04 20:30:00", user_id: 9, invite_msg: "Get ready for the quest!", start_msg: "Have fun Questing!", final_msg: "Great job on the Quest!"},
  {name: "Quest10", description: "Quest10 of awesomeness", start: "2017-07-04 21:30:00", user_id: 10, invite_msg: "Get ready for the quest!", start_msg: "Have fun Questing!", final_msg: "Great job on the Quest!"},
  {name: "Dave's 40th Birthday Quest of Awesomeness", description: "This is going to be a super fun quest to celebrate your 40th Birthday!!!", start: "2017-10-10 10:30:00", user_id: 22, invite_msg: "To celebrate your 40 years of life, this quest is going to take you to some memorable places to reminisce with old friends but create memories with new friends. Make sure you wear something comfortable, prepare for an active day, and don't forget your phone charger!", start_msg: "Okay- it's GO TIME! To complete this quest, you need to complete all of the tasks. You can skip tasks if necessary, but only do that if absolutely necessary. If you get stuck along the way, text or call me! Remember, take pictures or videos and post them to Facebook with the the '#DaveIz40' and '#AmazingQuest' hash tags so I can capture your memories and track your progress! Remember to have fun and be present in the moment!", final_msg: "I hope you had an amazing time and captured your memories along the way!"},
  ])

Task.create!([
  {name: "Stranger Things",
    description: "Head south on NW 5th until you reach NW 28th Street and turn east. Continue down that street until you find the building with the ginormous safety pin sticking out
    of it. When you find it, take a selfie with the safety pin and post it to IG with #StrangerThings. Enter the name of the cafe as the answer to move on to your next task.",
    answer: "Brothers & Brawlers",
    quest_id: 1,
    clue1: "It's on the north side of the street.",
    clue2: "The building is solid black. If you see stripes- you've gone too far.",
    clue3: "The name is something like Siblings & Strikers.",
    clue_timer: 2,
    answer_check: false,
    answer_comment: "Awesome! You got it! This place is cool...head inside to check it out before you head on to your next task if you want.",
    skip_comment: "Really- this early in the quest you are already being lazy?! This is soooooo simple!!!!"},
  {name: "Colors Everywhere!!!",
    description: "This next task will not be quite so easy. To solve this next task, you'll need to figure out where to go next. Somewhere in Wynwood is a location where you'll trip
    over tourists any day of the year. It's a very colorful place that changes from time-to-time. Head there and enter the name of the location to proceed to your next task.",
    answer: "Wynwood Walls",
    quest_id: 1,
    clue1: "It's southeast of your current location.",
    clue2: "The name is an alliteration like 'Wild Wild West'.",
    clue3: "It's right next to the Wynwood Kitchen!",
    clue_timer: 2,
    answer_check: false,
    answer_comment: "Ya- that was another easy one. Take some time to wander around and take some pics here. It's a really neat place with a gift shop!",
    skip_comment: "Ugh! This is an easy one to quit on...why are you quitting so easily?!"},
  {name: "Oxymorons All Around",
    description: "For your next task we're going to treat you to a type of art that many don't often associate with Wynwood or South Florida. To pass this next task, you'll need to figure
    out where to go and answer a question. Not far from where you are now, is a place that has a drink named after a curious collection of houses a mile off the Florida coast. Find the
    location and enter the name of that drink to move on to your next task. If you get to this location before the top of the hour, you can go on a free tour!",
    answer: "Stiltville Pilsner",
    quest_id: 1,
    clue1: "Drink Art, Make Beer!",
    clue2: "Circus clowns walk on these.",
    clue3: "Look south of Key Biscayne on Google Maps!",
    clue_timer: 1,
    answer_check: true,
    answer_comment: "Awesome! Enjoy a cold drink while you are here!!! One more task to go!",
    skip_comment: "Why would you quit on this one?! It's fun!!!"},
  {name: "Task4",
    description: "Task 4 of Quest 1",
    answer: "Task Answer",
    quest_id: 1,
    clue1: "Something Witty to Help You!",
    clue2: "Something sarcastic to anger you!",
    clue3: "Something snarky to really piss you off!",
    clue_timer: 2,
    answer_check: false,
    answer_comment: "Great job!",
    skip_comment: "Quitter!"},
  {name: "Task5", description: "Task 5 of Quest 1", answer: "Task Answer", quest_id: 1, clue1: "Something Witty to Help You!", clue2: "Something sarcastic to anger you!", clue3: "Something snarky to really piss you off!", clue_timer: 2, answer_check: false, answer_comment: "Great job!", skip_comment: "Quitter!"},
  {name: "Task1", description: "Task 1 of Quest 2", answer: "Task Answer", quest_id: 2, clue1: "Something Witty to Help You!", clue2: "Something sarcastic to anger you!", clue3: "Something snarky to really piss you off!", clue_timer: 2, answer_check: false, answer_comment: "Great job!", skip_comment: "Quitter!"},
  {name: "Task2", description: "Task 2 of Quest 2", answer: "Task Answer", quest_id: 2, clue1: "Something Witty to Help You!", clue2: "Something sarcastic to anger you!", clue3: "Something snarky to really piss you off!", clue_timer: 2, answer_check: false, answer_comment: "Great job!", skip_comment: "Quitter!"},
  {name: "Task3", description: "Task 3 of Quest 2", answer: "Task Answer", quest_id: 2, clue1: "Something Witty to Help You!", clue2: "Something sarcastic to anger you!", clue3: "Something snarky to really piss you off!", clue_timer: 2, answer_check: false, answer_comment: "Great job!", skip_comment: "Quitter!"},
  {name: "Task4", description: "Task 4 of Quest 2", answer: "Task Answer", quest_id: 2, clue1: "Something Witty to Help You!", clue2: "Something sarcastic to anger you!", clue3: "Something snarky to really piss you off!", clue_timer: 2, answer_check: false, answer_comment: "Great job!", skip_comment: "Quitter!"},
  {name: "Task5", description: "Task 5 of Quest 2", answer: "Task Answer", quest_id: 2, clue1: "Something Witty to Help You!", clue2: "Something sarcastic to anger you!", clue3: "Something snarky to really piss you off!", clue_timer: 2, answer_check: false, answer_comment: "Great job!", skip_comment: "Quitter!"},
  {name: "Task1", description: "Task 1 of Quest 3", answer: "Task Answer", quest_id: 3, clue1: "Something Witty to Help You!", clue2: "Something sarcastic to anger you!", clue3: "Something snarky to really piss you off!", clue_timer: 2, answer_check: false, answer_comment: "Great job!", skip_comment: "Quitter!"},
  {name: "Task2", description: "Task 2 of Quest 3", answer: "Task Answer", quest_id: 3, clue1: "Something Witty to Help You!", clue2: "Something sarcastic to anger you!", clue3: "Something snarky to really piss you off!", clue_timer: 2, answer_check: false, answer_comment: "Great job!", skip_comment: "Quitter!"},
  {name: "Task3", description: "Task 3 of Quest 3", answer: "Task Answer", quest_id: 3, clue1: "Something Witty to Help You!", clue2: "Something sarcastic to anger you!", clue3: "Something snarky to really piss you off!", clue_timer: 2, answer_check: false, answer_comment: "Great job!", skip_comment: "Quitter!"},
  {name: "Task1", description: "Task 1 of Quest 4", answer: "Task Answer", quest_id: 4, clue1: "Something Witty to Help You!", clue2: "Something sarcastic to anger you!", clue3: "Something snarky to really piss you off!", clue_timer: 2, answer_check: false, answer_comment: "Great job!", skip_comment: "Quitter!"},
  {name: "Task2", description: "Task 2 of Quest 4", answer: "Task Answer", quest_id: 4, clue1: "Something Witty to Help You!", clue2: "Something sarcastic to anger you!", clue3: "Something snarky to really piss you off!", clue_timer: 2, answer_check: false, answer_comment: "Great job!", skip_comment: "Quitter!"},
  {name: "Task3", description: "Task 3 of Quest 4", answer: "Task Answer", quest_id: 4, clue1: "Something Witty to Help You!", clue2: "Something sarcastic to anger you!", clue3: "Something snarky to really piss you off!", clue_timer: 2, answer_check: false, answer_comment: "Great job!", skip_comment: "Quitter!"},
  {name: "Task4", description: "Task 4 of Quest 4", answer: "Task Answer", quest_id: 4, clue1: "Something Witty to Help You!", clue2: "Something sarcastic to anger you!", clue3: "Something snarky to really piss you off!", clue_timer: 2, answer_check: false, answer_comment: "Great job!", skip_comment: "Quitter!"},
  {name: "Task5", description: "Task 5 of Quest 4", answer: "Task Answer", quest_id: 4, clue1: "Something Witty to Help You!", clue2: "Something sarcastic to anger you!", clue3: "Something snarky to really piss you off!", clue_timer: 2, answer_check: false, answer_comment: "Great job!", skip_comment: "Quitter!"},
  {name: "Task6", description: "Task 6 of Quest 4", answer: "Task Answer", quest_id: 4, clue1: "Something Witty to Help You!", clue2: "Something sarcastic to anger you!", clue3: "Something snarky to really piss you off!", clue_timer: 2, answer_check: false, answer_comment: "Great job!", skip_comment: "Quitter!"},
  {name: "Task7", description: "Task 7 of Quest 4", answer: "Task Answer", quest_id: 4, clue1: "Something Witty to Help You!", clue2: "Something sarcastic to anger you!", clue3: "Something snarky to really piss you off!", clue_timer: 2, answer_check: false, answer_comment: "Great job!", skip_comment: "Quitter!"},
  {name: "Task1", description: "Task 1 of Quest 5", answer: "Task Answer", quest_id: 5, clue1: "Something Witty to Help You!", clue2: "Something sarcastic to anger you!", clue3: "Something snarky to really piss you off!", clue_timer: 2, answer_check: false, answer_comment: "Great job!", skip_comment: "Quitter!"},
  {name: "Task2", description: "Task 2 of Quest 5", answer: "Task Answer", quest_id: 5, clue1: "Something Witty to Help You!", clue2: "Something sarcastic to anger you!", clue3: "Something snarky to really piss you off!", clue_timer: 2, answer_check: false, answer_comment: "Great job!", skip_comment: "Quitter!"},
  {name: "Task3", description: "Task 3 of Quest 5", answer: "Task Answer", quest_id: 5, clue1: "Something Witty to Help You!", clue2: "Something sarcastic to anger you!", clue3: "Something snarky to really piss you off!", clue_timer: 2, answer_check: false, answer_comment: "Great job!", skip_comment: "Quitter!"},
  {name: "Task1", description: "Task 1 of Quest 6", answer: "Task Answer", quest_id: 6, clue1: "Something Witty to Help You!", clue2: "Something sarcastic to anger you!", clue3: "Something snarky to really piss you off!", clue_timer: 2, answer_check: false, answer_comment: "Great job!", skip_comment: "Quitter!"},
  {name: "Task2", description: "Task 2 of Quest 6", answer: "Task Answer", quest_id: 6, clue1: "Something Witty to Help You!", clue2: "Something sarcastic to anger you!", clue3: "Something snarky to really piss you off!", clue_timer: 2, answer_check: false, answer_comment: "Great job!", skip_comment: "Quitter!"},
  {name: "Task3", description: "Task 3 of Quest 6", answer: "Task Answer", quest_id: 6, clue1: "Something Witty to Help You!", clue2: "Something sarcastic to anger you!", clue3: "Something snarky to really piss you off!", clue_timer: 2, answer_check: false, answer_comment: "Great job!", skip_comment: "Quitter!"},
  {name: "Task4", description: "Task 4 of Quest 6", answer: "Task Answer", quest_id: 6, clue1: "Something Witty to Help You!", clue2: "Something sarcastic to anger you!", clue3: "Something snarky to really piss you off!", clue_timer: 2, answer_check: false, answer_comment: "Great job!", skip_comment: "Quitter!"},
  {name: "Task5", description: "Task 5 of Quest 6", answer: "Task Answer", quest_id: 6, clue1: "Something Witty to Help You!", clue2: "Something sarcastic to anger you!", clue3: "Something snarky to really piss you off!", clue_timer: 2, answer_check: false, answer_comment: "Great job!", skip_comment: "Quitter!"},
  {name: "Task6", description: "Task 6 of Quest 6", answer: "Task Answer", quest_id: 6, clue1: "Something Witty to Help You!", clue2: "Something sarcastic to anger you!", clue3: "Something snarky to really piss you off!", clue_timer: 2, answer_check: false, answer_comment: "Great job!", skip_comment: "Quitter!"},
  {name: "Task7", description: "Task 7 of Quest 6", answer: "Task Answer", quest_id: 6, clue1: "Something Witty to Help You!", clue2: "Something sarcastic to anger you!", clue3: "Something snarky to really piss you off!", clue_timer: 2, answer_check: false, answer_comment: "Great job!", skip_comment: "Quitter!"},
  {name: "Task1", description: "Task 1 of Quest 7", answer: "Task Answer", quest_id: 7, clue1: "Something Witty to Help You!", clue2: "Something sarcastic to anger you!", clue3: "Something snarky to really piss you off!", clue_timer: 2, answer_check: false, answer_comment: "Great job!", skip_comment: "Quitter!"},
  {name: "Task2", description: "Task 2 of Quest 7", answer: "Task Answer", quest_id: 7, clue1: "Something Witty to Help You!", clue2: "Something sarcastic to anger you!", clue3: "Something snarky to really piss you off!", clue_timer: 2, answer_check: false, answer_comment: "Great job!", skip_comment: "Quitter!"},
  {name: "Task3", description: "Task 3 of Quest 7", answer: "Task Answer", quest_id: 7, clue1: "Something Witty to Help You!", clue2: "Something sarcastic to anger you!", clue3: "Something snarky to really piss you off!", clue_timer: 2, answer_check: false, answer_comment: "Great job!", skip_comment: "Quitter!"},
  {name: "Task4", description: "Task 4 of Quest 7", answer: "Task Answer", quest_id: 7, clue1: "Something Witty to Help You!", clue2: "Something sarcastic to anger you!", clue3: "Something snarky to really piss you off!", clue_timer: 2, answer_check: false, answer_comment: "Great job!", skip_comment: "Quitter!"},
  {name: "Task5", description: "Task 5 of Quest 7", answer: "Task Answer", quest_id: 7, clue1: "Something Witty to Help You!", clue2: "Something sarcastic to anger you!", clue3: "Something snarky to really piss you off!", clue_timer: 2, answer_check: false, answer_comment: "Great job!", skip_comment: "Quitter!"},
  {name: "Task1", description: "Task 1 of Quest 8", answer: "Task Answer", quest_id: 8, clue1: "Something Witty to Help You!", clue2: "Something sarcastic to anger you!", clue3: "Something snarky to really piss you off!", clue_timer: 2, answer_check: false, answer_comment: "Great job!", skip_comment: "Quitter!"},
  {name: "Task2", description: "Task 2 of Quest 8", answer: "Task Answer", quest_id: 8, clue1: "Something Witty to Help You!", clue2: "Something sarcastic to anger you!", clue3: "Something snarky to really piss you off!", clue_timer: 2, answer_check: false, answer_comment: "Great job!", skip_comment: "Quitter!"},
  {name: "Task3", description: "Task 3 of Quest 8", answer: "Task Answer", quest_id: 8, clue1: "Something Witty to Help You!", clue2: "Something sarcastic to anger you!", clue3: "Something snarky to really piss you off!", clue_timer: 2, answer_check: false, answer_comment: "Great job!", skip_comment: "Quitter!"},
  {name: "Task4", description: "Task 4 of Quest 8", answer: "Task Answer", quest_id: 8, clue1: "Something Witty to Help You!", clue2: "Something sarcastic to anger you!", clue3: "Something snarky to really piss you off!", clue_timer: 2, answer_check: false, answer_comment: "Great job!", skip_comment: "Quitter!"},
  {name: "Task5", description: "Task 5 of Quest 8", answer: "Task Answer", quest_id: 8, clue1: "Something Witty to Help You!", clue2: "Something sarcastic to anger you!", clue3: "Something snarky to really piss you off!", clue_timer: 2, answer_check: false, answer_comment: "Great job!", skip_comment: "Quitter!"},
  {name: "Task1", description: "Task 1 of Quest 9", answer: "Task Answer", quest_id: 9, clue1: "Something Witty to Help You!", clue2: "Something sarcastic to anger you!", clue3: "Something snarky to really piss you off!", clue_timer: 2, answer_check: false, answer_comment: "Great job!", skip_comment: "Quitter!"},
  {name: "Task2", description: "Task 2 of Quest 9", answer: "Task Answer", quest_id: 9, clue1: "Something Witty to Help You!", clue2: "Something sarcastic to anger you!", clue3: "Something snarky to really piss you off!", clue_timer: 2, answer_check: false, answer_comment: "Great job!", skip_comment: "Quitter!"},
  {name: "Task3", description: "Task 3 of Quest 9", answer: "Task Answer", quest_id: 9, clue1: "Something Witty to Help You!", clue2: "Something sarcastic to anger you!", clue3: "Something snarky to really piss you off!", clue_timer: 2, answer_check: false, answer_comment: "Great job!", skip_comment: "Quitter!"},
  {name: "Task1", description: "Task 1 of Quest 10", answer: "Task Answer", quest_id: 10, clue1: "Something Witty to Help You!", clue2: "Something sarcastic to anger you!", clue3: "Something snarky to really piss you off!", clue_timer: 2, answer_check: false, answer_comment: "Great job!", skip_comment: "Quitter!"},
  {name: "Task2", description: "Task 2 of Quest 10", answer: "Task Answer", quest_id: 10, clue1: "Something Witty to Help You!", clue2: "Something sarcastic to anger you!", clue3: "Something snarky to really piss you off!", clue_timer: 2, answer_check: false, answer_comment: "Great job!", skip_comment: "Quitter!"},
  {name: "Task3", description: "Task 3 of Quest 10", answer: "Task Answer", quest_id: 10, clue1: "Something Witty to Help You!", clue2: "Something sarcastic to anger you!", clue3: "Something snarky to really piss you off!", clue_timer: 2, answer_check: false, answer_comment: "Great job!", skip_comment: "Quitter!"},
  {name: "Feed Me!", description: "The way to a man's heart is through his stomache. Go to our favorite breakfast place and tell the hostess that 'Dave has arrived!' Follower her instructions and enter your answer below.", answer: "Weston Diner", quest_id: 11, clue1: "Where is the best place for grits?", clue2: "If you really need another clue, there is an issue!", clue3: "It's the Weston Diner!!!", clue_timer: 2, answer_check: false, answer_comment: "Great job! Keep going!", skip_comment: "Quitter!"},
  {name: "Up and Away!!!", description: "When we met, you wanted to go to Airborne School but you gave that up for me. But now, you can feel like you are parachuting without jumping out of an airplane! Find the next place and shout 'Airborne!!!!' when you walk inside.", answer: "iFLY Ft Lauderdale", quest_id: 11, clue1: "You have to FLY but i love to FLY!", clue2: "It's right of hwy 84 just east of Weston", clue3: "Go to 11690 West State Road 84, Davie, Florida 33325", clue_timer: 2, answer_check: false, answer_comment: "Great job!", skip_comment: "Chicken!!!"},
  {name: "Hard Target", description: "Now that you earned your Airborne Wings, you need to make sure you can hit your target. Head to this next place and find an employee and let them know 'Dave is in da houzzz!!!'", answer: "2600 Davie Rd, Davie, FL 33314", quest_id: 11, clue1: "This place is really modern!", clue2: "Oh sure, you can get a German Marksmanship Badge but you can't find a good range!", clue3: "Head east on 595 and exit at Davie Rd.", clue_timer: 2, answer_check: false, answer_comment: "I knew you could do it!", skip_comment: "Really?! This one?!"},
  {name: "Riddle me this!", description: "Okay, the easy ones are behind you. Now you have to earn this one! Head to Markham Park and look for a clue once you arrive. It'll be obvious to start!", answer: "40", quest_id: 11, clue1: "Text Kimi to see if she can help you!", clue2: "Go to the Dog Park!", clue3: "Text me and I'll tell you where to go.", clue_timer: 3, answer_check: false, answer_comment: "Finally! That one was tough!!!", skip_comment: "I will never let you live this down!"},
  ])

Role.create!([
  {role: true, user_id: 1, quest_id: 1},
  {role: false, user_id: 2, quest_id: 1},
  {role: false, user_id: 3, quest_id: 1},
  {role: true, user_id: 4, quest_id: 2},
  {role: false, user_id: 5, quest_id: 2},
  {role: false, user_id: 6, quest_id: 2},
  {role: true, user_id: 3, quest_id: 3},
  {role: false, user_id: 1, quest_id: 3},
  {role: false, user_id: 5, quest_id: 3},
  {role: false, user_id: 6, quest_id: 3},
  {role: true, user_id: 1, quest_id: 4},
  {role: false, user_id: 7, quest_id: 4},
  {role: true, user_id: 8, quest_id: 5},
  {role: false, user_id: 7, quest_id: 5},
  {role: false, user_id: 9, quest_id: 5},
  {role: true, user_id: 7, quest_id: 6},
  {role: false, user_id: 4, quest_id: 6},
  {role: false, user_id: 5, quest_id: 7},
  {role: true, user_id: 3, quest_id: 7},
  {role: false, user_id: 4, quest_id: 8},
  {role: false, user_id: 10, quest_id: 8},
  {role: true, user_id: 6, quest_id: 8},
  {role: false, user_id: 2, quest_id: 9},
  {role: true, user_id: 10, quest_id: 9},
  {role: true, user_id: 2, quest_id: 10},
  {role: false, user_id: 3, quest_id: 10},
  {role: false, user_id: 9, quest_id: 10},
  {role: true, user_id: 22, quest_id: 11},
  {role: false, user_id: 23, quest_id: 11}
  ])
